// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace XmlRegions
{
    internal sealed partial class Vsix
    {
        public const string Id = "XmlRegions.bc2b6443-6808-4c2c-935c-2a3ede9a8efd";
        public const string Name = "XML Regions";
        public const string Description = @"Adds support for region comments in XML and AXAML(Avalonia XAML) files .";
        public const string Language = "en-US";
        public const string Version = "1.1.1";
        public const string Author = "Tobias Hein";
        public const string Tags = "XML, regions, AXAML, Avalonia";
        public const bool IsPreview = false;
    }
}
