// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace XmlRegions
{
    internal sealed partial class Vsix
    {
        public const string Id = "XmlRegions.bc2b6443-6808-4c2c-935c-2a3ede9a8efd";
        public const string Name = "XML Regions";
        public const string Description = @"Adds support for region comments in XML files.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Tobias Hein";
        public const string Tags = "xml, regions";
    }
}
